# Generated by Django 5.2.17 on 2026-10-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tienda',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
