# Generated by Django 5.2.17 on 2026-10-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_tienda_categoria_tienda_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'producto'), name='unique_product_per_cart'),
        ),
    ]
