# Generated by Django 5.2.17 on 2026-10-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_producto_categoria_producto_imagen_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
